<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RestoreAdditionalProjectSources>https://nuget.bepinex.dev/v3/index.json</RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.16" />
  </ItemGroup>

  <!-- Проверь эту секцию -->
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>Assembly-CSharp.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
